module-name: kyma-environment-broker
rc-tag: 1.5.0
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker:1.5.0
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-deprovision-retrigger-job:1.5.0
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environments-cleanup-job:1.5.0
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-runtime-reconciler:1.5.0
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-archiver-job:1.5.0
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-expirator-job:1.5.0
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-cleanup-job:1.5.0
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-sync:1.5.0
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
    - "testing/**"
    - "**/automock/**"
    - "**/*fake*.go"
    - "**/*mock*.go"
