module-name: kyma-environment-broker
rc-tag: 1.3.2
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker:1.3.2
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-deprovision-retrigger-job:1.3.2
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environments-cleanup-job:1.3.2
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-runtime-reconciler:1.3.2
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-trial-cleanup-job:1.3.2
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-cleanup-job:1.3.2
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
    - "testing/**"
    - "**/automock/**"
    - "**/*fake*.go"
    - "**/*mock*.go"
