apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
data:
  trialRegionMapping.yaml: |-
{{- with .Values.trialRegionsMapping }}
{{ tpl . $ | indent 4 }}
{{- end }}
  sapConvergedCloudPlanRegionMappings.yaml: |-
{{- with .Values.sapConvergedCloudPlanRegionMappings }}
{{ tpl . $ | indent 4 }}
{{- end }}
  skrOIDCDefaultValues.yaml: |-
{{- with .Values.skrOIDCDefaultValues }}
{{ tpl . $ | indent 4 }}
{{- end }}
  skrDNSProvidersValues.yaml: |-
{{- with .Values.skrDNSProvidersValues }}
{{ tpl . $ | indent 4 }}
{{- end }}
  catalog.yaml: |-
{{ .Files.Get "files/catalog.yaml" | indent 4 }}
  freemiumWhitelistedGlobalAccountIds.yaml: |-
{{- with .Values.freemiumWhitelistedGlobalAccountIds }}
{{ tpl . $ | indent 4 }}
{{- end }}
