# This file contains values for KEB chart needed to install it in CN region.

global:
  images:
    cloudsql_proxy_image: "europe-docker.pkg.dev/kyma-project/prod/tpi/cloudsql-docker/gce-proxy:v1.33.16-133356bc"
    container_registry:
      path: 113663649212.dkr.ecr.cn-northwest-1.amazonaws.com.cn/kcp-cn
    schema_migrator:
      dir: ""
      version: "v20240307-f250dc83" # do not update along with the other images
    kyma_environment_broker:
      dir:
      version: "1.8.2"
    database:
      cloudsqlproxy:
        enabled: false

archiving:
    enabled: true
    dryRun: false
cleaning:
    enabled: true
    dryRun: false

avs:
  disabled: true

broker:
  events:
    enabled: true
binding:
    enabled: false


dashboardConfig:
    enabled: true
    landscapeURL: https://dashboard.kyma.cloud.sap # **CN**

edp:
    disabled: true

enableKubeconfigURLLabel: true

enablePlans: azure,gcp,azure_lite,aws,trial,free,sap-converged-cloud

ias:
    disabled: true

includeAdditionalParamsInSchema: true

# must be configured
kubeconfig:
    allowOrigins: https://dashboard.kyma.cloud.sap
    clientID: client-id-to-set
    issuerURL: https://kyma.accounts.ondemand.com

kymaVersion: 2.20.0
lifecycleManager:
    disabled: true

infrastructureManager:
    disabled: true


oidc:
    client: client-id-to-set
    issuer: https://kyma.accounts.ondemand.com
    keysURL: https://kyma.accounts.ondemand.com/oauth2/certs

osbUpdateProcessingEnabled: true
provisioner:
    dumpRequests: false
    gardenerClusterStepTimeout: 3m
runtimeAllowedPrincipals: |-
    - cluster.local/ns/kcp-system/sa/kcp-kyma-metrics-collector
    - cluster.local/ns/monitoring-system/sa/mop-agent
serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: proxy-user@sap-ti-dx-kyma-mps-prod.iam.gserviceaccount.com
serviceManager:
    overrideMode: "Always"

showTrialExpirationInfo: true

subaccountCleanup:
    enabled: false
subaccountsIdsToShowTrialExpirationInfo: all


trialCleanup:
    enabled: false
freeCleanup:
    enabled: false
runtimeReconciler:
    enabled: false
deprovisionRetrigger:
    enabled: false

subaccountSync:
    enabled: false

metricsv2:
    enabled: true
    operationResultRetentionPeriod: 336h
    operationResultPoolingInterval: 1m
    operationStatsPoolingInterval: 1m
onlyOneFreePerGA: true
freemiumWhitelistedGlobalAccountIds: |-
    whitelist:
      - d9994f8f-7e46-42a8-b2c1-1bfff8d2fe05
showFreeExpirationInfo: true
freeDocsURL:
    https://help.sap.com/docs/btp/sap-business-technology-platform/available-plans-in-kyma-environment


serviceMonitor:
  enabled: false

imagePullSecret: "k8s-ecr-login-renew-docker-secret"
