name: Validate KEB chart install (reusable)

on:
  workflow_call:
    inputs:
      last-k3s-versions:
        description: number of the most recent K3s versions to be used
        required: false
        default: 1
        type: string
      release:
        description: 'Determines if the workflow is called from release'
        default: "true"
        type: string
      version:
        description: 'Release version'
        default: "0.0.0.0"
        type: string

jobs:
  validate-keb-helm-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
      with:
        files: |
          .github/**
          resources/**
          scripts/**
          Makefile
          **/*.sh
          .github/**
          cmd/**
          common/**
          files/**
          internal/**
          utils/edp-registrator/**
          .golangci.yml
          Dockerfile.*
          go.mod
          go.sum
          **/*.go

    - name: Prepare chart for next KEB version
      if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
      run: |
        if [ "${{ inputs.release }}" == "true" ]; then
          scripts/bump_keb_chart.sh ${{ inputs.version }} "release"
        else
          scripts/bump_keb_chart.sh PR-${{ inputs.version }} "pr"
        fi

    - name: Validate KEB helm chart
      if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
      run: |
        cd resources/keb
        helm template .
  
  prepare-tests:
    runs-on: ubuntu-latest
    needs: validate-keb-helm-chart
    outputs:
      versions: ${{ steps.get-versions.outputs.k3s_versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        with:
          files: |
            .github/**
            resources/**
            scripts/**
            Makefile
            **/*.sh
            .github/**
            cmd/**
            common/**
            files/**
            internal/**
            utils/edp-registrator/**
            .golangci.yml
            Dockerfile.*
            go.mod
            go.sum

      - id: get-versions
        name: Get K3s versions
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        # prepare json representing GitHub matrix:
        # {"include": [
        #    {"version":"v1.26.10+k3s1"},
        #      ...
        #    {"version":"v1.28.3+k3s1"}
        # ]
        # }
        run: |
          VERSIONS=($(./scripts/testing/get-latest-k3s-releases.sh ${{ inputs.last-k3s-versions }}))
          MATRIX_AS_JSON=$(echo ${VERSIONS[*]} | awk 'END {printf "{\"include\":[";for (i = 1; i < NF; i++) printf "{\"version\":%s},",$i;printf "{\"version\":%s}]}",$i }'|jq -c)
          echo "k3s_versions=${MATRIX_AS_JSON}" >> "${GITHUB_OUTPUT}"

  run-keb-chart-matrix:
    runs-on: ubuntu-latest
    needs: prepare-tests
    timeout-minutes: 5
    strategy:
      matrix: ${{ fromJSON(needs.prepare-tests.outputs.versions) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        with:
          files: |
            .github/**
            resources/**
            scripts/**
            Makefile
            **/*.sh
            .github/**
            cmd/**
            common/**
            files/**
            internal/**
            utils/edp-registrator/**
            .golangci.yml
            Dockerfile.*
            go.mod
            go.sum

      - name: Prepare K3s cluster and docker registry
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        run: "./scripts/testing/k3s-setup.sh ${{ matrix.version }} --wait"

      - name: Create namespaces
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        run: |
          kubectl create namespace kcp-system
          kubectl create namespace kyma-system
          kubectl create namespace istio-system

      - name: Install istio
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        run: |
          helm repo add istio https://istio-release.storage.googleapis.com/charts
          helm install istio-base istio/base -n istio-system --set defaultRevision=default
          
      - name: Install Prometheus Operator for ServiceMonitor
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        run: |
          kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml

      - name: Install Postgres
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        run: |
          kubectl create -f scripts/testing/yaml/postgres -n kcp-system
      
      - name: Prepare fake gardener credentials
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        run: |
          KCFG=$(kubectl config view --raw)
          kubectl create secret generic gardener-credentials --from-literal=kubeconfig="$KCFG" -n kcp-system

      - name: Prepare chart for next KEB version
        run: |
          if [ "${{ inputs.release }}" == "true" ]; then
            scripts/bump_keb_chart.sh ${{ inputs.version }} "release"
          else
            scripts/bump_keb_chart.sh PR-${{ inputs.version }} "pr"
          fi

      - name: Deploy KEB helm chart
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        run: |
          cd resources/keb
          if [ "${{ inputs.release }}" == "true" ]; then
            helm install keb ../keb --namespace kcp-system -f values.yaml --set global.database.embedded.enabled=false --set testConfig.kebDeployment.useAnnotations=true --debug --wait
          else
            helm install keb ../keb --namespace kcp-system -f values.yaml --set global.database.embedded.enabled=false --set testConfig.kebDeployment.useAnnotations=true --set global.images.container_registry.path="europe-docker.pkg.dev/kyma-project/dev" --debug --wait
          fi

  confirm-keb-chart-tests-result:
    needs: run-keb-chart-matrix
    runs-on: ubuntu-latest
    if: success() 
    outputs:
      success: ${{ steps.set-output.outputs.success }}
    steps:
      - name: Confirm KEB chart tests result
        id: set-output
        run: echo "success=true" >> "${GITHUB_OUTPUT}"

  finish-keb-chart-tests:
    runs-on: ubuntu-latest
    if: always()
    needs: confirm-keb-chart-tests-result
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        with:
          files: |
            .github/**
            resources/**
            scripts/**
            Makefile
            **/*.sh
            .github/**
            cmd/**
            common/**
            files/**
            internal/**
            utils/edp-registrator/**
            .golangci.yml
            Dockerfile.*
            go.mod
            go.sum

      - name: Check KEB chart tests result
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        run: |
          if [ "${{ needs.confirm-keb-chart-tests-result.outputs.success }}" != "true" ]; then
            echo "KEB chart tests failed"
            exit 1
          fi
          echo "KEB chart tests passed"
